### ISSUE TITLE
[BUG] The response body is not fully displayed

### ISSUE THREAD

**Issue by YGHS4** [zcyberseclab/zscan#22]
### Current Behavior
The response body does not include the POC content. This is actually a vulnerability.
![image](https://github.com/user-attachments/assets/2377d52a-1f16-484e-b8c3-7be88719353c)
![image](https://github.com/user-attachments/assets/0d07035e-6d1a-412e-a445-df8ac547ff7c)

### Expected Behavior
Ability to display vulnerability content.

### Steps To Reproduce
``` json
 "zlmediakit": {
    "body": [
      "文件索引"
    ]
  }
```
``` go
go run .\cmd\main.go -target 112.36.22.55:10003
```

### Environment
Go: go1.22.2 windows/amd64
Zscan：v1.0.7

**Comment by YGHS4** [comment]
- target:112.36.22.55:10003
- poc:
Please create a zlmediakit directory in the templates directory, and change the json to yml and put it in the directory.
[zlmediakit-directorytraversal.json](https://github.com/user-attachments/files/17974743/zlmediakit-directorytraversal.json)

**Comment by zcyberseclab** [comment]
change poc as
```
cve-id: zlmediakit-directorytraversal
rules:
- method: GET
  path: /record
  headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
      Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
      Accept-Encoding: gzip, deflate
      Connection: close
      Upgrade-Insecure-Requests: 1
  expression: 'response.status ==  200 && response.body.bcontains(b"文件索引:/record") '
severity: high
type: directorytraversal
```
